In [5]:
import pandas as pd

uscities = pd.read_csv('uscities.csv')
df = pd.read_csv('../../data_collection/plein_de_data/fandom_trait√©es.csv')
t=0
for state in df.State.unique():
    print(state)
    s=0
    for city in df[df.State == state].Town.unique():
        if city not in uscities[uscities.state_id == state].city.unique():
            print(city)
            s+=1
    print(s)
    t+=s
print(t)

AL
0
AK
0
AZ
0
AR
0
CA
0
CO
0
CT
0
DE
0
DC
0
FL
0
GA
0
HI
0
ID
0
IL
0
IN
0
IA
0
KS
0
KY
0
LA
0
ME
0
MD
0
MA
0
MI
Canton
Chesterfield
Clinton Township
Commerce
Fort Gratiot
Jonesboro
New Hudson
Saint Johns
Sault Sainte Marie
Shelby Township
Van Buren Twp.
White Lake
Ysplanti
13
MN
0
MS
0
MO
0
MT
0
NE
0
NV
0
NH
0
NJ
0
NM
0
NY
0
NC
0
ND
0
OH
0
OK
0
OR
0
PA
0
RI
0
SC
0
SD
0
TN
0
TX
0
UT
0
VT
0
VA
0
WA
0
WV
0
WI
0
WY
0
13

In [41]:
df[df.Town == 'Oakwood']

,Store_id,State,Town,Street,Category,Opening_date,Closing_date
1257,3627,GA,Oakwood,3875 Mundy Mill Rd.,Walmart Supercenter,2007-05-09,NaN

In [36]:
for state in uscities.state_id.unique():
    s = uscities[uscities.state_id == state].groupby('city').count()
    print(state)
    print(s[s.city_ascii>2])
    print("==========================================================================")

CA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
CT
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
FL
        city_ascii  state_id  state_name  county_fips  county_name  lat  lng  \
city
Midway           3         3           3            3            3    3    3

        population  density  source  military  incorporated  timezone  \
city
Midway           3        3       3         3             3         3

        ranking  zips  id
city
Midway        3     3   3
==========================================================================
GA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
IN
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
ME
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MD
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
NY
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
IL
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
TX
             city_ascii  state_id  state_name  county_fips  county_name  lat  \
city
Chula Vista           3         3           3            3            3    3

             lng  population  density  source  military  incorporated  \
city
Chula Vista    3           3        3       3         3             3

             timezone  ranking  zips  id
city
Chula Vista         3        3     3   3
==========================================================================
PA
            city_ascii  state_id  state_name  county_fips  county_name  lat  \
city
Georgetown           3         3           3            3            3    3
Oakland              3         3           3            3            3    3

            lng  population  density  source  military  incorporated  \
city
Georgetown    3           3        3       3         3             3
Oakland       3           3        3       3         3             3

            timezone  ranking  zips  id
city
Georgetown         3        3     3   3
Oakland            3        3     3   3
==========================================================================
DC
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
AZ
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MI
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
WA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MN
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
CO
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
NV
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MO
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
OR
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
PR
             city_ascii  state_id  state_name  county_fips  county_name  lat  \
city
San Antonio           3         3           3            3            3    3

             lng  population  density  source  military  incorporated  \
city
San Antonio    3           3        3       3         3             3

             timezone  ranking  zips  id
city
San Antonio         3        3     3   3
==========================================================================
OH
         city_ascii  state_id  state_name  county_fips  county_name  lat  lng  \
city
Oakwood           3         3           3            3            3    3    3

         population  density  source  military  incorporated  timezone  \
city
Oakwood           3        3       3         3             3         3

         ranking  zips  id
city
Oakwood        3     3   3
==========================================================================
NC
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
VA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
WI
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
RI
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
UT
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
TN
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
KY
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
LA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
OK
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
HI
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
NE
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
NM
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
AL
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
SC
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
IA
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
KS
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
AR
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
ID
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MS
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
NJ
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
AK
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
NH
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
ND
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
WV
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
SD
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
DE
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
MT
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
VT
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================
WY
Empty DataFrame
Columns: [city_ascii, state_id, state_name, county_fips, county_name, lat, lng, population, density, source, military, incorporated, timezone, ranking, zips, id]
Index: []
==========================================================================

In [33]:
uscities.head()

,city,city_ascii,state_id,state_name,county_fips,county_name,lat,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
0,City of Industry,City of Industry,CA,California,6037,Los Angeles,34.0050,-117.939,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
1,Avon,Avon,CT,Connecticut,9003,Hartford,41.7944,-72.8578,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
2,Branford,Branford,CT,Connecticut,9009,New Haven,41.2778,-72.7997,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
3,Cromwell,Cromwell,CT,Connecticut,9007,Middlesex,41.5950,-72.6453,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown
4,East Windsor,East Windsor,CT,Connecticut,9003,Hartford,41.9167,-72.5578,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown