In [1]:
import pandas as pd
import numpy as np

### Philibert's dataset

In [2]:
panelist = pd.read_table("../../Nielsen/panelists_2016.tsv").set_index('Household_Cd')[['Fips_State_Cd', 'Fips_State_Desc', 'Fips_County_Cd', 'Fips_County_Desc', 'Panelist_ZipCd']]
panelist['household_county_fips'] = np.vectorize(int)(panelist.Fips_State_Cd * 1e3 + panelist.Fips_County_Cd)
panelist['household_zip3'] = panelist.Panelist_ZipCd // 100
panelist = panelist[['Fips_State_Desc', 'Fips_County_Desc', 'household_county_fips', 'household_zip3']].rename(columns={'Fips_State_Desc': 'household_state', 'Fips_County_Desc': 'household_county'})

purchases = pd.read_csv("../../Nielsen/purchases_subset_2016.csv")
purchases['upc_price'] = purchases.total_price_paid / purchases.quantity
purchases = purchases[['trip_code_uc', 'upc', 'upc_price']]

trips = pd.read_table("../../Nielsen/trips_2016.tsv", parse_dates=['purchase_date']).set_index('trip_code_uc')[['purchase_date', 'retailer_code', 'store_code_uc', 'store_zip3', 'household_code']]

In [4]:
zip_to_state = pd.read_table('zip_prefixes.txt', header=0, names=['zip3','state', 'distib_center', 'towns'])[['zip3', 'state']]

non_null = trips[trips.store_code_uc != 0]
non_null = non_null.merge(zip_to_state, left_on='store_zip3', right_on='zip3')[['purchase_date', 'retailer_code', 'store_code_uc', 'state', 'store_zip3', 'household_code']].rename(columns={'state': 'store_state'})

non_null_merged = non_null.merge(panelist, left_on='household_code', right_on='Household_Cd')[['retailer_code', 'store_code_uc', 'store_state', 'store_zip3', 'household_state', 'household_county_fips', 'household_county', 'household_zip3']]

before_deletion = len(non_null_merged)
non_null_state = non_null_merged[non_null_merged.household_state == non_null_merged.store_state] # TOUT RENOMMER

non_null_zip3 = non_null_state[non_null_state.household_zip3 == non_null_state.store_zip3]

df = non_null_zip3
                                                                    
from random import choice

def my_mode(self):
    return choice(list(pd.Series.mode(self)))
                            
store_loc = df.groupby(['store_code_uc'])[['retailer_code', 'store_state', 'household_county_fips', 'household_county']].agg(my_mode).rename(columns={'household_county_fips': 'guessed_store_county_fips', 'household_county': 'guessed_store_county'})
                                                                                               
def my_max(x):
    try:
        return max(x)
    except:
        return x
def my_min(x):
    try:
        return min(x)
    except:
        return x
def my_sum(x):
    try:
        return sum(x)
    except:
        return x
def my_len(x):
    try:
        return len(x)
    except:
        return 1
                                                                                            
trips_loc = trips[trips.store_code_uc != 0].reset_index().merge(store_loc.reset_index(), on=['retailer_code', 'store_code_uc']).set_index('trip_code_uc')
                                                                                               
prices = purchases.merge(trips_loc, on='trip_code_uc')[['trip_code_uc','purchase_date', 'retailer_code', 'store_code_uc', 'store_state', 'guessed_store_county', 'guessed_store_county_fips', 'upc', 'upc_price']]
prices['purchase_month'] = prices.purchase_date.dt.month

### Trials

#### Candidates

In [6]:
df_test = prices.groupby(['retailer_code'])['store_code_uc'].nunique().rename("nb_of_stores_per_retailer").to_frame()
pd.set_option("display.max_rows", None)
df_test.sort_values("nb_of_stores_per_retailer", ascending=False)

               nb_of_stores_per_retailer
retailer_code
6920                                3289
3997                                2352
4914                                1761
4904                                1662
6901                                1332
130                                 1177
181                                  762
32                                   683
4901                                 617
79                                   606
156                                  585
24                                   578
848                                  512
6905                                 414
6904                                 396
248                                  391
9                                    368
817                                  333
272                                  287
120                                  250
6921                                 246
174                                  224
42                                   224
151                                  221
408                                  204
89                                   193
117                                  193
184                                  182
236                                  173
111                                  168
843                                  157
6                                    155
890                                  152
240                                  146
839                                  136
90                                   131
29                                   126
290                                  124
294                                  123
210                                  122
257                                  122
209                                  121
34                                   115
45                                   113
158                                  113
128                                  106
858                                  103
857                                  101
129                                   99
68                                    94
2                                     93
201                                   84
239                                   83
194                                   80
36                                    79
221                                   77
60                                    71
47                                    69
274                                   67
199                                   64
356                                   63
6907                                  63
296                                   60
28                                    57
867                                   56
182                                   56
285                                   55
144                                   54
153                                   52
183                                   52
914                                   51
926                                   50
126                                   50
888                                   49
281                                   47
50                                    45
868                                   44
873                                   43
92                                    41
152                                   39
265                                   39
379                                   38
72                                    38
849                                   37
21                                    37
847                                   36
155                                   35
927                                   34
185                                   34
916                                   33
956                                   32
123                                   31
727                                   31
275                                   30
874                                   30
69                                    29
311                                   28
125                                   28
527                                   28
277                                   27
222                                   26
363                                   25
315                                   24
904                                   24
112                                   24
951                                   23
104                                   23
341                                   23
283                                   22
62                                    22
215                                   22
348                                   22
878                                   22
805                                   21
351                                   21
977                                   20
113                                   20
883                                   20
304                                   20
884                                   19
920                                   19
313                                   18
887                                   18
164                                   18
4926                                  17
327                                   17
889                                   17
4954                                  17
869                                   17
978                                   16
338                                   16
284                                   16
976                                   16
947                                   16
770                                   16
940                                   16
227                                   16
97                                    16
852                                   16
882                                   15
875                                   15
455                                   15
856                                   15
905                                   15
929                                   14
982                                   14
807                                   14
200                                   14
77                                    14
291                                   13
8                                     13
915                                   13
912                                   13
906                                   13
899                                   13
483                                   13
354                                   13
886                                   13
345                                   13
911                                   12
948                                   12
908                                   12
172                                   12
924                                   12
287                                   11
597                                   11
935                                   11
987                                   11
953                                   11
954                                   11
51                                    11
386                                   11
896                                   11
328                                   11
980                                   10
346                                   10
724                                   10
900                                   10
439                                   10
485                                   10
224                                   10
279                                   10
186                                   10
219                                    9
931                                    9
722                                    9
955                                    9
161                                    9
863                                    9
801                                    9
876                                    9
891                                    9
949                                    9
406                                    8
336                                    8
4961                                   8
295                                    8
216                                    8
644                                    8
41                                     8
988                                    7
381                                    7
407                                    7
961                                    7
804                                    7
885                                    7
76                                     7
349                                    7
844                                    7
842                                    7
903                                    7
910                                    7
6919                                   7
266                                    6
898                                    6
289                                    6
902                                    6
877                                    6
913                                    6
897                                    6
946                                    6
52                                     6
957                                    6
941                                    6
697                                    6
921                                    6
418                                    6
984                                    5
157                                    5
928                                    5
188                                    5
101                                    5
834                                    5
909                                    5
419                                    5
444                                    5
989                                    5
925                                    5
18                                     4
950                                    4
824                                    4
149                                    4
178                                    4
102                                    4
983                                    4
917                                    4
197                                    4
841                                    4
343                                    4
952                                    4
235                                    4
81                                     4
851                                    4
286                                    4
854                                    4
958                                    4
307                                    4
960                                    4
975                                    4
934                                    3
932                                    3
990                                    3
13                                     3
124                                    3
617                                    3
302                                    3
634                                    3
427                                    3
98                                     3
808                                    3
392                                    3
387                                    3
114                                    3
390                                    3
542                                    3
901                                    3
319                                    3
134                                    3
880                                    3
115                                    3
959                                    2
332                                    2
429                                    2
360                                    2
918                                    2
979                                    2
361                                    2
968                                    2
970                                    2
972                                    2
551                                    2
288                                    2
813                                    2
985                                    2
865                                    2
933                                    2
57                                     2
168                                    2
241                                    2
833                                    2
819                                    2
944                                    2
945                                    2
95                                     2
683                                    2
655                                    2
986                                    2
922                                    2
616                                    2
861                                    2
326                                    1
118                                    1
254                                    1
143                                    1
20                                     1
78                                     1
991                                    1
919                                    1
335                                    1
806                                    1
907                                    1
895                                    1
879                                    1
855                                    1
53                                     1
936                                    1
938                                    1
708                                    1
342                                    1
612                                    1
596                                    1
534                                    1
967                                    1
973                                    1
384                                    1
981                                    1
966                                    1

#### Tests

In [62]:
r_code_list = [6920, 3997, 4914, 4904, 6901, 130, 181, 32, 4901, 79, 156, 24]

In [63]:
SC_list = [("NJ", "OCEAN", '2016-07-13', "SC"),("SC", "DARLINGTON", '2016-05-11', "SC"),("SD", "MINNEHAHA", '2016-08-24', "SC"),
           ("TN", "RUTHERFORD", '2016-08-24', "SC"), ("TX", "TOM GREEN", '2016-05-11', "SC"),
           ("VA", "ROCKINGHAM", '2016-07-13', "SC")]
NM_list = [("FL","MARION",'2016-08-03',"NM"), ("LA", "TERREBONNE", '2016-08-31', "NM"),("NM", "OTERO", '2016-06-15', "NM")]

In [64]:
for r_code in r_code_list :
    print("_________________\n")
    print(r_code)
    for list_element in SC_list :
        state, county, opening_date, store_type = list_element
        print(state, county, store_type)
        prices_t = prices[(prices.store_state == state)
                         &(prices.guessed_store_county == county)&(prices.retailer_code == r_code)].sort_values("purchase_month")
        prices_t["purchase_before_opening"] = prices_t.purchase_date < opening_date
        prices_t = prices_t.groupby("store_code_uc")["purchase_before_opening"].any()
        #.rename("store_code_uc").to_frame()
        pd.set_option("display.max_rows", None)
        print(prices_t)

_________________

6920
NJ OCEAN SC
store_code_uc
4841059    True
7764479    True
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
store_code_uc
4246331    True
8244765    True
Name: purchase_before_opening, dtype: bool
SD MINNEHAHA SC
store_code_uc
2886136    True
3757133    True
5767438    True
Name: purchase_before_opening, dtype: bool
TN RUTHERFORD SC
store_code_uc
3916789     True
4739715     True
6989482     True
8288188    False
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
store_code_uc
465045     True
3511697    True
Name: purchase_before_opening, dtype: bool
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

3997
NJ OCEAN SC
store_code_uc
1227685    True
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
store_code_uc
5175473    True
7171299    True
Name: purchase_before_opening, dtype: bool
TN RUTHERFORD SC
Series([], Name: purchase_before_opening, dtype: bool)
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
store_code_uc
3958751     True
5648987    False
Name: purchase_before_opening, dtype: bool
_________________

4914
NJ OCEAN SC
store_code_uc
1963829     True
7121301    False
7933759     True
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
store_code_uc
7644731    False
Name: purchase_before_opening, dtype: bool
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
store_code_uc
144306    True
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

4904
NJ OCEAN SC
store_code_uc
1721522    False
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
store_code_uc
5507032     True
6483071    False
6597269     True
Name: purchase_before_opening, dtype: bool
TN RUTHERFORD SC
store_code_uc
3494668    True
7783982    True
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
store_code_uc
729037     False
5238856    False
Name: purchase_before_opening, dtype: bool
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

6901
NJ OCEAN SC
store_code_uc
1738864     True
4707141    False
4838174    False
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
store_code_uc
2467447    True
7967964    True
Name: purchase_before_opening, dtype: bool
TN RUTHERFORD SC
store_code_uc
6880098    True
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
store_code_uc
7394448    True
Name: purchase_before_opening, dtype: bool
_________________

130
NJ OCEAN SC
Series([], Name: purchase_before_opening, dtype: bool)
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
store_code_uc
635101     True
1292766    True
1973465    True
2134058    True
3539989    True
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
store_code_uc
5732322    True
Name: purchase_before_opening, dtype: bool
_________________

181
NJ OCEAN SC
Series([], Name: purchase_before_opening, dtype: bool)
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
store_code_uc
2565989     True
4890180     True
7214507    False
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

32
NJ OCEAN SC
Series([], Name: purchase_before_opening, dtype: bool)
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
Series([], Name: purchase_before_opening, dtype: bool)
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

4901
NJ OCEAN SC
store_code_uc
1607454    True
4114984    True
8080766    True
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
Series([], Name: purchase_before_opening, dtype: bool)
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

79
NJ OCEAN SC
Series([], Name: purchase_before_opening, dtype: bool)
SC DARLINGTON SC
store_code_uc
465144    True
Name: purchase_before_opening, dtype: bool
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
store_code_uc
1916424    True
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
store_code_uc
7087217    True
Name: purchase_before_opening, dtype: bool
_________________

156
NJ OCEAN SC
store_code_uc
5961114    True
Name: purchase_before_opening, dtype: bool
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
store_code_uc
4516095    True
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)
_________________

24
NJ OCEAN SC
Series([], Name: purchase_before_opening, dtype: bool)
SC DARLINGTON SC
Series([], Name: purchase_before_opening, dtype: bool)
SD MINNEHAHA SC
Series([], Name: purchase_before_opening, dtype: bool)
TN RUTHERFORD SC
store_code_uc
1601600    False
7547416    False
Name: purchase_before_opening, dtype: bool
TX TOM GREEN SC
Series([], Name: purchase_before_opening, dtype: bool)
VA ROCKINGHAM SC
Series([], Name: purchase_before_opening, dtype: bool)